name: Payment API CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: SonarCloud SAST
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=ashwini07091996devsecops
            -Dsonar.projectKey=Ashwini07091996_DevSecOps
            -Dsonar.qualitygate.wait=true

      - name: Build Docker image
        run: |
          docker build -t payment-api:${{ github.sha }} .

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: payment-api:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: '1'
